name: Run Dataminer

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs every day at midnight and midday
  workflow_dispatch: # Allows manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run the dataminer
        run: node index.js
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GUILDED_WEBHOOK: ${{ secrets.GUILDED_WEBHOOK }}

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Reisonancia"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update data"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GUILDED_WEBHOOK: ${{ secrets.GUILDED_WEBHOOK }}